version: '3.8'

networks:
  serving_prod_net:
    external: true

services:
  fastapi_serving:
    build: .
    container_name: fastapi_model_serving
    volumes:
      - ../artifacts:/app/artifacts
      - ../data:/app/data
      - ../scripts:/app/scripts
      - report_data:/app/reporting  # Shared volume for report data
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - serving_prod_net

volumes:
  report_data: