version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"  # Mapper le port 8888 du conteneur à l'hôte
    volumes:
      - ./app:/app  # Monter le répertoire app dans le conteneur
